# Generated by Django 3.0.8 on 2024-08-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20240623_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GridLayout',
        ),
    ]
